//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLineProduction.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.8\\sistematica\\AREA_FIRMWARE\\SmartLine\\Compilati")]
        public string FW_folder {
            get {
                return ((string)(this["FW_folder"]));
            }
            set {
                this["FW_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Commander")]
        public string Commander_path {
            get {
                return ((string)(this["Commander_path"]));
            }
            set {
                this["Commander_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.8\\sistematica\\AREA_PRODOTTO\\SMARTLINE\\")]
        public string Doc_folder {
            get {
                return ((string)(this["Doc_folder"]));
            }
            set {
                this["Doc_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("178|89")]
        public string Settings_Brother_SL {
            get {
                return ((string)(this["Settings_Brother_SL"]));
            }
            set {
                this["Settings_Brother_SL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("178|89")]
        public string Settings_Brother_Antiman {
            get {
                return ((string)(this["Settings_Brother_Antiman"]));
            }
            set {
                this["Settings_Brother_Antiman"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.0.8\\TJ-4120TN_SL")]
        public string Settings_Brother_Default {
            get {
                return ((string)(this["Settings_Brother_Default"]));
            }
            set {
                this["Settings_Brother_Default"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SERVER208\\SQLEXPRESS;Initial Catalog=SISTEMATICA_FACTORY;Persist Secu" +
            "rity Info=True;User ID=sa;Password=aavesp19!;")]
        public string SISTEMATICA_FACTORYConnectionString {
            get {
                return ((string)(this["SISTEMATICA_FACTORYConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.208\\SQLEXPRESS;Initial Catalog=SISTEMATICA_FACTORY;Persist " +
            "Security Info=True;User ID=sa;Password=aavesp19!")]
        public string SISTEMATICA_FACTORYConnectionString1 {
            get {
                return ((string)(this["SISTEMATICA_FACTORYConnectionString1"]));
            }
        }
    }
}
